EXCEPTIONS_SRC = exceptions.cpp
EXCEPCIONSTD_SRC = excepciones_estandar.cpp

exception: $(EXCEPTIONS_SRC)
	g++ $(EXCEPTIONS_SRC) -o $@

	./$@

estandar: $(EXCEPCIONSTD_SRC)
	g++ $(EXCEPCIONSTD_SRC) -o $@

	./$@